# Generated by GitHub Copilot on 2026-04-12

from django.db import migrations, models
import django.db.models.deletion
import uuid


def forwards_create_pharmacy_profiles(apps, schema_editor):
    WebsiteSetup = apps.get_model('core', 'WebsiteSetup')
    Pharmacy = apps.get_model('pharmacies', 'Pharmacy')
    Product = apps.get_model('pharmacies', 'Product')

    for setup in WebsiteSetup.objects.select_related('user').all():
        user = setup.user
        base_name = (getattr(user, 'name', '') or '').strip()
        default_name = f"{base_name} Pharmacy" if base_name else 'My Pharmacy'

        pharmacy, _ = Pharmacy.objects.get_or_create(
            user_id=user.id,
            defaults={
                'website_setup_id': setup.id,
                'name': default_name,
                'template_id': setup.template_id,
            },
        )

        updates = []
        if not pharmacy.website_setup_id:
            pharmacy.website_setup_id = setup.id
            updates.append('website_setup_id')
        if pharmacy.template_id is None and setup.template_id is not None:
            pharmacy.template_id = setup.template_id
            updates.append('template_id')
        if not pharmacy.name:
            pharmacy.name = default_name
            updates.append('name')
        if updates:
            pharmacy.save(update_fields=updates)

        Product.objects.filter(website_setup_id=setup.id, pharmacy__isnull=True).update(pharmacy_id=pharmacy.id)


def backwards_clear_pharmacy_links(apps, schema_editor):
    Product = apps.get_model('pharmacies', 'Product')
    Product.objects.update(pharmacy_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatbot_models'),
        ('pharmacies', '0002_alter_product_options_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/')),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to='core.user')),
                ('website_setup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to='core.websitesetup')),
            ],
            options={
                'db_table': 'pharmacies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pharmacies.pharmacy'),
        ),
        migrations.RunPython(forwards_create_pharmacy_profiles, backwards_clear_pharmacy_links),
    ]
