# Generated by Django 4.2.7 on 2026-04-13 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_chat_conver_website_31d4df_idx_chat_conver_website_6703b2_idx_and_more'),
        ('pharmacies', '0003_pharmacy_profile_and_product_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyTemplatePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.PositiveIntegerField(db_index=True)),
                ('template_name', models.CharField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('visa', 'Visa/Mastercard'), ('fawry', 'Fawry')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_purchases', to='pharmacies.pharmacy')),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_purchases', to='core.websitesetup')),
            ],
            options={
                'db_table': 'pharmacy_template_purchases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pharmacytemplatepurchase',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'template_id'), name='uniq_pharmacy_template_purchase'),
        ),
    ]
