# Generated by Django 4.2.7 on 2026-04-14 22:10

from django.db import migrations, models
from django.db.models import Q


def forwards_mark_paid_orders(apps, schema_editor):
    PharmacyOrder = apps.get_model('pharmacies', 'PharmacyOrder')
    PharmacyOrder.objects.filter(
        Q(payment_method='card') | Q(status='completed')
    ).update(payment_status='paid')


def backwards_reset_payment_status(apps, schema_editor):
    PharmacyOrder = apps.get_model('pharmacies', 'PharmacyOrder')
    PharmacyOrder.objects.update(payment_status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_pharmacyorder_pharmacyorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='payment_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('paid', 'Paid')],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
        migrations.RunPython(forwards_mark_paid_orders, backwards_reset_payment_status),
    ]
