# Generated by Django 4.2.7 on 2026-05-02 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rename_chat_conver_website_31d4df_idx_chat_conver_website_6703b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.department')),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_doctors',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_pages', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_builder_pages',
                'unique_together': {('website_setup', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the hospital, e.g. America/New_York', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_setup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hospitals.doctor')),
            ],
            options={
                'db_table': 'hospital_doctor_schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HERO_BLOCK', 'Hero Block'), ('DOCTORS_LIST_BLOCK', 'Doctors List Block'), ('DEPARTMENTS_BLOCK', 'Departments Block'), ('BOOKING_BUTTON_BLOCK', 'Booking Button Block'), ('BOOKING_FORM_BLOCK', 'Booking Form Block'), ('TEXT_BLOCK', 'Text Block'), ('IMAGE_BLOCK', 'Image Block'), ('CONTACT_BLOCK', 'Contact Block')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hospitals.page')),
            ],
            options={
                'db_table': 'hospital_builder_blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospitals.doctor')),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointments', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_appointments',
                'indexes': [models.Index(fields=['doctor', 'start_datetime'], name='hospital_ap_doctor__047836_idx')],
                'unique_together': {('doctor', 'start_datetime')},
            },
        ),
    ]
