# Generated by Django 4.2.7 on 2026-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_doctor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['specific_date', 'day_of_week', 'start_time']},
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
