# Generated by Django 4.2.7 on 2026-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='patients_treated',
            field=models.CharField(default='50k+', help_text="Total patients treated (e.g., '50k+', '100k+')", max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='years_of_excellence',
            field=models.IntegerField(default=25, help_text='Years the hospital has been operating'),
        ),
    ]
