# Generated by Django 4.2.7 on 2026-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatbot_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='chat_conver_website_6703b2_idx',
            old_name='chat_conver_website_31d4df_idx',
        ),
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='chat_conver_website_f0cf30_idx',
            old_name='chat_conver_website_eb9b6e_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_convers_0a903c_idx',
            old_name='chat_messag_convers_913d16_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_role_ddd811_idx',
            old_name='chat_messag_role_2fdd3c_idx',
        ),
        migrations.AlterField(
            model_name='templateaisettings',
            name='model_id',
            field=models.CharField(default='microsoft/Phi-3-mini-4k-instruct', max_length=255),
        ),
    ]
