# Generated by Django 4.2.7 on 2026-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_chat_conver_website_31d4df_idx_chat_conver_website_6703b2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetup',
            name='one_time_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='websitesetup',
            name='plan_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('AI', 'AI'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='websitesetup',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesetup',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='INACTIVE', max_length=20),
        ),
    ]
