# Generated by Django 4.2.7 on 2026-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_websitesetup_one_time_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetup',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='INACTIVE', max_length=20),
        ),
    ]
